'use client'

import { useState } from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import {
  Activity, Archive, ArrowUpRight, BarChart3, Bell, ChevronDown, Copy, File,
  FileCode2, FileImage, FileText, Folder, HardDrive, LayoutGrid, Menu, MoreHorizontal,
  Plus, Search, Settings2, Share2, ShieldCheck, Sparkles, UploadCloud, Users, X,
} from 'lucide-react'
import { Button } from '@/components/ui/button'

const nav = [
  { href: '/dashboard', label: 'My files', icon: LayoutGrid },
  { href: '/simulator', label: 'Storage simulator', icon: Activity },
  { href: '/admin', label: 'Admin console', icon: ShieldCheck },
]
const files = [
  { name: 'Brand guidelines.pdf', size: '8.4 MB', type: 'pdf', color: 'violet' },
  { name: 'Product roadmap.fig', size: '24.1 MB', type: 'fig', color: 'orange' },
  { name: 'Q1 campaign assets', size: '1.8 GB', type: 'folder', color: 'blue' },
  { name: 'Launch video.mp4', size: '128 MB', type: 'video', color: 'pink' },
  { name: 'Engineering specs', size: '482 MB', type: 'folder', color: 'cyan' },
  { name: 'Financial model.xlsx', size: '2.1 MB', type: 'sheet', color: 'emerald' },
]

function Sidebar() {
  const pathname = usePathname()
  return <aside className="hidden w-64 shrink-0 border-r border-white/[0.07] bg-[#101217]/80 p-5 lg:flex lg:flex-col">
    <div className="mb-10 flex items-center gap-3 px-2"><div className="flex size-9 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-300 to-blue-600 text-[#071014] shadow-[0_0_24px_rgba(34,211,238,.2)]"><Archive className="size-5" /></div><div><div className="text-sm font-semibold tracking-wide text-white">vault<span className="text-cyan-300">.io</span></div><div className="text-[10px] uppercase tracking-[.18em] text-zinc-500">distributed storage</div></div></div>
    <div className="mb-3 px-2 text-[10px] font-semibold uppercase tracking-[.18em] text-zinc-600">Workspace</div>
    <nav className="flex flex-col gap-1">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition-colors ${pathname === href ? 'bg-white/[0.09] text-white shadow-inner' : 'text-zinc-500 hover:bg-white/[0.04] hover:text-zinc-200'}`}><Icon className="size-[17px]" />{label}{href === '/simulator' && <span className="ml-auto size-1.5 rounded-full bg-emerald-400" />}</Link>)}</nav>
    <div className="mt-8 mb-3 px-2 text-[10px] font-semibold uppercase tracking-[.18em] text-zinc-600">Collections</div>
    <nav className="flex flex-col gap-1"><div className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-zinc-500"><Sparkles className="size-[17px] text-amber-300" />Starred</div><div className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-zinc-500"><Share2 className="size-[17px] text-violet-300" />Shared with me</div><div className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-zinc-500"><HardDrive className="size-[17px] text-cyan-300" />Storage</div></nav>
    <div className="mt-auto rounded-2xl border border-white/[0.07] bg-white/[0.03] p-4"><div className="mb-2 flex items-center justify-between text-xs"><span className="text-zinc-400">Storage used</span><span className="text-white">68%</span></div><div className="mb-3 h-1.5 overflow-hidden rounded-full bg-white/[0.08]"><div className="h-full w-[68%] rounded-full bg-gradient-to-r from-cyan-400 to-blue-500" /></div><div className="text-[11px] text-zinc-500">680 GB of 1 TB</div><button className="mt-3 text-xs font-medium text-cyan-300 hover:text-cyan-200">Manage plan <ArrowUpRight className="ml-1 inline size-3" /></button></div>
  </aside>
}

function Header({ onUpload }: { onUpload: () => void }) { return <header className="flex h-20 items-center gap-3 border-b border-white/[0.07] px-5 sm:px-8"><button className="text-zinc-400 lg:hidden"><Menu className="size-5" /></button><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-zinc-500" /><input className="h-10 w-full rounded-xl border border-white/[0.08] bg-white/[0.035] pl-10 pr-4 text-sm text-white outline-none placeholder:text-zinc-600 focus:border-cyan-300/40" placeholder="Search files and folders" /></div><button className="hidden size-9 items-center justify-center rounded-xl text-zinc-500 hover:bg-white/[0.05] sm:flex"><Bell className="size-4" /></button><div className="flex items-center gap-2 border-l border-white/[0.08] pl-3"><div className="flex size-8 items-center justify-center rounded-full bg-gradient-to-br from-amber-200 to-orange-500 text-xs font-bold text-[#31200b]">JD</div><div className="hidden text-left sm:block"><div className="text-xs font-medium text-zinc-200">Jordan Davis</div><div className="text-[10px] text-zinc-600">Pro workspace</div></div><ChevronDown className="hidden size-3.5 text-zinc-600 sm:block" /></div></header> }

function UploadDialog({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-2xl border border-white/[0.1] bg-[#15181e] p-6 shadow-2xl"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-lg font-semibold text-white">Upload files</h2><p className="mt-1 text-sm text-zinc-500">Add files to your distributed vault.</p></div><button onClick={onClose} className="text-zinc-500 hover:text-white"><X className="size-5" /></button></div><div className="flex h-40 flex-col items-center justify-center rounded-xl border border-dashed border-cyan-300/30 bg-cyan-300/[0.03]"><UploadCloud className="mb-3 size-8 text-cyan-300" /><div className="text-sm text-zinc-300">Drop files here or <span className="text-cyan-300">browse</span></div><div className="mt-1 text-xs text-zinc-600">Up to 5 GB per file</div></div><div className="mt-5 rounded-xl border border-white/[0.07] bg-white/[0.025] p-3"><div className="flex items-center gap-3"><FileText className="size-5 text-violet-300" /><div className="flex-1"><div className="text-xs text-zinc-300">Q1-report-final.pdf</div><div className="mt-2 h-1 overflow-hidden rounded bg-white/[0.08]"><div className="h-full w-3/4 rounded bg-cyan-300" /></div></div><span className="text-xs text-cyan-300">75%</span></div></div><div className="mt-6 flex justify-end gap-2"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button className="bg-cyan-300 text-[#071014] hover:bg-cyan-200" onClick={onClose}>Upload files</Button></div></div></div> }

function FileIcon({ type, color }: { type: string; color: string }) { const Icon = type === 'folder' ? Folder : type === 'pdf' || type === 'sheet' ? FileText : type === 'fig' ? FileCode2 : FileImage; return <div className={`flex size-11 items-center justify-center rounded-xl bg-${color}-400/10`}><Icon className={`size-5 text-${color}-300`} /></div> }
function FileCard({ file, onShare }: { file: typeof files[number]; onShare: () => void }) { const [open, setOpen] = useState(false); return <div className="group relative rounded-2xl border border-white/[0.07] bg-white/[0.025] p-3 transition-all hover:-translate-y-0.5 hover:border-cyan-300/25 hover:bg-white/[0.045]"><div className="mb-5 flex h-28 items-center justify-center rounded-xl bg-gradient-to-br from-white/[0.05] to-transparent"><FileIcon type={file.type} color={file.color} /></div><div className="flex items-center gap-2"><FileIcon type={file.type} color={file.color} /><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium text-zinc-200">{file.name}</div><div className="mt-0.5 text-[11px] text-zinc-600">{file.size}</div></div><button onClick={() => setOpen(!open)} className="rounded-lg p-1 text-zinc-600 hover:bg-white/[0.08] hover:text-white"><MoreHorizontal className="size-4" /></button></div>{open && <div className="absolute right-3 top-36 z-10 w-32 rounded-xl border border-white/10 bg-[#1b1e25] p-1 shadow-xl"><button onClick={onShare} className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-xs text-zinc-300 hover:bg-white/[0.07]"><Share2 className="size-3.5" />Share</button><button className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-xs text-zinc-300 hover:bg-white/[0.07]"><FileText className="size-3.5" />Rename</button><button className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-xs text-red-300 hover:bg-red-400/10"><X className="size-3.5" />Delete</button></div>}</div> }

function Dashboard() { const [upload, setUpload] = useState(false); const [share, setShare] = useState(false); return <Shell onUpload={() => setUpload(true)}><div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs text-zinc-600"><span>Workspace</span><span>/</span><span className="text-zinc-400">My files</span></div><h1 className="text-2xl font-semibold tracking-tight text-white">Good morning, Jordan <span className="text-amber-300">✦</span></h1><p className="mt-1 text-sm text-zinc-500">Here&apos;s what&apos;s happening in your vault.</p></div><Button onClick={() => setUpload(true)} className="w-fit bg-cyan-300 text-[#071014] hover:bg-cyan-200"><Plus data-icon="inline-start" />New upload</Button></div><div className="mb-8 grid gap-3 sm:grid-cols-3"><Stat label="Total files" value="1,284" note="+12 this week" icon={File} /><Stat label="Shared with you" value="48" note="6 need review" icon={Users} /><Stat label="Storage used" value="680 GB" note="68% of 1 TB" icon={HardDrive} /></div><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold text-white">Recent files</h2><button className="text-xs text-cyan-300">View all <ArrowUpRight className="ml-1 inline size-3" /></button></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4">{files.map((file) => <FileCard key={file.name} file={file} onShare={() => setShare(true)} />)}</div></div>{upload && <UploadDialog onClose={() => setUpload(false)} />}{share && <ShareDialog onClose={() => setShare(false)} />}</Shell> }
function Stat({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof File }) { return <div className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4"><div className="mb-4 flex items-center justify-between"><span className="text-xs text-zinc-500">{label}</span><Icon className="size-4 text-zinc-600" /></div><div className="text-xl font-semibold text-white">{value}</div><div className="mt-1 text-[11px] text-emerald-300">{note}</div></div> }
function ShareDialog({ onClose }: { onClose: () => void }) { const [copied, setCopied] = useState(false); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-white/[0.1] bg-[#15181e] p-6"><div className="mb-5 flex justify-between"><div><h2 className="text-lg font-semibold text-white">Share file</h2><p className="mt-1 text-sm text-zinc-500">Anyone with this link can view.</p></div><button onClick={onClose} className="text-zinc-500"><X className="size-5" /></button></div><div className="flex gap-2"><input readOnly value="vault.io/s/8f2kLmQ" className="min-w-0 flex-1 rounded-lg border border-white/[0.1] bg-white/[0.04] px-3 text-sm text-zinc-300 outline-none" /><Button onClick={() => setCopied(true)} variant="outline" className="border-white/10 text-zinc-300">{copied ? 'Copied' : <><Copy data-icon="inline-start" />Copy</>}</Button></div></div></div> }

function Simulator() { const nodes = [['8001','Active','42.8 GB','1,284','cyan'],['8002','Active','39.2 GB','1,102','emerald'],['8003','Active','41.6 GB','1,198','violet'],['8004','Offline','0 GB','0','red']]; return <Shell><div className="mx-auto max-w-7xl"><div className="mb-8 flex items-end justify-between"><div><div className="mb-3 text-xs text-zinc-600">Infrastructure / Storage simulator</div><h1 className="text-2xl font-semibold text-white">Storage simulator</h1><p className="mt-1 text-sm text-zinc-500">Monitor the distributed storage ring in real time.</p></div><Button variant="outline" className="border-white/10 text-zinc-300"><Activity data-icon="inline-start" />Refresh</Button></div><div className="mb-6 grid gap-3 sm:grid-cols-3"><Stat label="Cluster health" value="75%" note="3 of 4 nodes active" icon={Activity} /><Stat label="Total chunks" value="3,584" note="+128 this hour" icon={Archive} /><Stat label="Replication factor" value="3x" note="All systems nominal" icon={ShieldCheck} /></div><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold text-white">Storage nodes</h2><div className="flex items-center gap-2 text-xs text-zinc-500"><span className="size-1.5 rounded-full bg-emerald-400" />Live telemetry</div></div><div className="grid gap-4 md:grid-cols-2">{nodes.map(([id,status,used,chunks,color]) => <div key={id} className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className={`flex size-10 items-center justify-center rounded-xl bg-${color}-400/10 font-mono text-xs text-${color}-300`}>:{id}</div><div><div className="font-medium text-white">Node {id}</div><div className="mt-1 flex items-center gap-2 text-xs text-zinc-500"><span className={`size-1.5 rounded-full ${status === 'Active' ? 'bg-emerald-400' : 'bg-red-400'}`} />{status}</div></div></div><button className="text-zinc-600"><Settings2 className="size-4" /></button></div><div className="mt-6 grid grid-cols-2 gap-4 border-t border-white/[0.07] pt-4"><div><div className="text-xs text-zinc-600">Storage used</div><div className="mt-1 text-lg text-zinc-200">{used}</div></div><div><div className="text-xs text-zinc-600">Chunks stored</div><div className="mt-1 text-lg text-zinc-200">{chunks}</div></div></div>{status === 'Active' && <div className="mt-4 h-1 overflow-hidden rounded-full bg-white/[0.07]"><div className={`h-full rounded-full bg-${color}-300`} style={{ width: `${id === '8001' ? 68 : id === '8002' ? 54 : 61}%` }} /></div>}</div>)}</div></div></Shell> }
function Admin() { return <Shell><div className="mx-auto max-w-7xl"><div className="mb-8"><div className="mb-3 text-xs text-zinc-600">System / Admin console</div><h1 className="text-2xl font-semibold text-white">Admin console</h1><p className="mt-1 text-sm text-zinc-500">Manage users, capacity, and system health.</p></div><div className="mb-8 grid gap-3 sm:grid-cols-3"><Stat label="System utilization" value="68.0%" note="Within healthy limits" icon={BarChart3} /><Stat label="Active users" value="248" note="+18 this month" icon={Users} /><Stat label="System uptime" value="99.98%" note="Last 30 days" icon={Activity} /></div><div className="overflow-hidden rounded-2xl border border-white/[0.07] bg-white/[0.025]"><div className="flex items-center justify-between border-b border-white/[0.07] p-5"><h2 className="text-sm font-semibold text-white">System users</h2><Button variant="outline" className="border-white/10 text-zinc-300"><Users data-icon="inline-start" />Invite user</Button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-white/[0.06] text-[11px] uppercase tracking-wider text-zinc-600"><tr><th className="px-5 py-3 font-medium">User</th><th className="px-5 py-3 font-medium">Role</th><th className="px-5 py-3 font-medium">Storage</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-white/[0.05]">{[['Jordan Davis','admin@admin.com','Admin','680 GB','Active'],['Maya Chen','maya@acme.co','Member','124 GB','Active'],['Liam Jones','liam@acme.co','Member','89 GB','Active'],['Noah Wilson','noah@acme.co','Viewer','12 GB','Pending']].map(([name,email,role,storage,status]) => <tr key={email} className="text-zinc-300"><td className="px-5 py-4"><div className="font-medium text-zinc-200">{name}</div><div className="mt-0.5 text-xs text-zinc-600">{email}</div></td><td className="px-5 py-4 text-xs text-zinc-400">{role}</td><td className="px-5 py-4 text-xs text-zinc-400">{storage}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-[10px] ${status === 'Active' ? 'bg-emerald-400/10 text-emerald-300' : 'bg-amber-400/10 text-amber-300'}`}>{status}</span></td><td className="px-5 py-4 text-right"><MoreHorizontal className="ml-auto size-4 text-zinc-600" /></td></tr>)}</tbody></table></div></div></div></Shell> }
function Shell({ children, onUpload }: { children: React.ReactNode; onUpload?: () => void }) { return <div className="min-h-screen bg-[#0b0d11] text-zinc-100"><div className="flex min-h-screen"><Sidebar /><main className="min-w-0 flex-1"><Header onUpload={onUpload ?? (() => {})} /><div className="p-5 sm:p-8">{children}</div></main></div></div> }
export { Dashboard, Simulator, Admin }
export default Dashboard
